### Implementation of fuzzy merge in Python with example

This was developed to handle a merge situation of two keys which didn't match completely but they need to be joined for further analyses.

When two columns don't look not exactly the same and we know that they are the ones that we have to join, we can use fuzzy merge which uses wildcart type join. Below is an example to explain the implementation

#### Creating Sample Dataframes

In [5]:
import pandas as pd
exact_df1 = pd.DataFrame({'exact_column': ['20561', '', '20563', '20564','12345'],
                    'Currency': ['EUR', 'EUR', 'EUR', 'USD','INR']})
fuzzy_df1 = pd.DataFrame({'fuzzy_column': ['20561', 'INV20562', 'INV20563BG', '','1234567'],
                    'Type': ['01', '03', '04', '02','05'],
                    'Amount': ['150', '175', '160', '180','328'],
                    'Comment': ['bla', 'bla', 'bla', 'bla','sdf']})

print(exact_df1.head())
print("\n")
print(fuzzy_df1.head())

  exact_column Currency
0        20561      EUR
1                   EUR
2        20563      EUR
3        20564      USD
4        12345      INR


  fuzzy_column Type Amount Comment
0        20561   01    150     bla
1     INV20562   03    175     bla
2   INV20563BG   04    160     bla
3                02    180     bla
4      1234567   05    328     sdf


The fuzzy_column from the fuzzy_df1 partially matches the exact_column from the exact_df1. below method can be used to join the two dataframes using these columns without any library function.

#### Fuzzy merge implementation - Preparation

In [6]:
## Defining lookup conditions
search_from_column = "exact_column"   # The one which has to be looked or searched(The exact column)
lookup_dataframe = fuzzy_df1   # the one with fuzzy matching columns
search_result_column = "fuzzy_column"    # the one where search has to be performed
fetch_value_column = "Amount"    # the one which has to be returned after a search match

# EMPTY VALUES IN THE VLOOKUP RELATED COLUMNS WOULD RESULT IN ERROR or UNDESIRABLE OUTPUT, SO REMOVE ROWS WITH EMPTY VALUES
exact_df1 = exact_df1.loc[~(exact_df1[search_from_column] == "")]   # Removing empty strings
fuzzy_df1 = fuzzy_df1.loc[~(fuzzy_df1[search_result_column] == "")] # Removing empty strings


# Make a copy of final dataframe to keep the looked up column
final = exact_df1.copy()


#### Fuzzy Merge - Function

In [7]:
# Define lookup function
def vlookup_fuzzy(lookup_value):
    negative = "Not Found"
    if(len(lookup_dataframe.loc[lookup_dataframe[search_result_column].str.contains(lookup_value), fetch_value_column]) == 1):
        return lookup_dataframe.loc[lookup_dataframe[search_result_column].str.contains(lookup_value), fetch_value_column].iloc[0]
    else:
        return negative

#### Results

In [8]:
# Applying this function to the final dataframe
final[fetch_value_column] = final[search_from_column].apply(vlookup_fuzzy)

# Print Results
final.head()

exact_column Currency     Amount
0        20561      EUR        150
2        20563      EUR        160
3        20564      USD  Not Found
4        12345      INR        328

Note that the row 2 has got the amount 160 fetched using matching part of the text from exact column 20563.